language: go
go:
- 1.7
notifications:
  email: false
sudo: required
services:
- docker
install: true
script: make
after_success:
- curl -s https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master/docker-build.sh
  | bash /dev/stdin enmasseproject/enmasse-rest .
- curl -s https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master/trigger-travis.sh
  | bash /dev/stdin
env:
  global:
  - GO15VENDOREXPERIMENT=1
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: S0lQUN9bNy76haaqaYppILxfp4jXVB+KCAStN9rRHHIGjyN/a4M0TuzOQ2mwjuroti14xS3zdZ3gQqBe2TIsHtO5J3WXN/txespZKajcFTg69a4CLjtIJdXAAPU3xRES5DxrzSVb0yMw6O8Ie0ePiAWFyyB9qQ1rRmt9Ep8Cx+GOw8ODNAv09pirRn/Ew7Bc7/1kvhBALtaTZixK67zgA+eFjLxTcJOGk0/7f2uk6aQ/wChvY8zx8kxn3pTS0utE7DLa+qKM6oom3IFh0RvqpZnzX9yZG2we0nwHghUb2HZ1hfVQsQ/Uq5E33Vzuja6bicCFZfOrd5b8kWCUNg6Bs3HnA6wBOeBH/spaOE+pCkt1uNAa9CjHqJoASBVX0bxwMWum43KDco4puavMXJd3GC7m0fiCjd3jvZLJ7IHC0izwLT/4MAbS9Z6+YH04OnGuzG+dVOwwhb8yTalFilwsLDMNQryGmBFf0c4QC9mL6tId9V9+CP4J+NCii0YOIWffxBV5ol9I/KKwHyk/60aFxZ+keFJfBRdwzWvW1D+FP+WgUrMQ0QwCFB8nmaSPLLiBi2WHJEwIOg7IGcWCB8eZXOaPiL0Kd3YwIc+cibRytAtnz69NXjWXBGFi2LcqRIIq3VdYC9+cSZ1NEBD4ZCnyKFVRyO/ywliMlJyAZJW6UaM=
  - secure: YzuR5VBxBQ7Fk4TtqKXc8PAUsMzviIYOND1WTdl5ibnTwhRB00Fet85phQns9aUvKCuNCkImKHmNEMta5jxD0TQK8s1cKhNpM1DCUxksdHyD1N4itlwG1Vvjb6dj3lqhyOtvKvBSzqHDywiDfg0jmWldSY7YsZWclSWaQDoeFo21oIwIVg8hPymvTbtkdWtY+S1MEaTWfavEfiG23zy2CqAAcEdrYlCUhVgw1Md+5XWTaU7RDSiyplrSo+GoSMsBXi5s+QADdtwhML/TRGZhHn9/HHyFKnGMwSD0CMdutxTXRPsf1ZwLjPtDrxPU8lgcJDe6Bo97TK1m6SW2fKqQE6x54Z0R53FbnKx4IeEDRkfIkWyaA9iA95k4aoX+a+ZkAwwScOoWrSPBVDBJaxwpyLNpXAytjZZN27Jtf2Gs/6NkbTdm1Ctdec1/buXFGhPQEuK0fVRbdXeWGEqEGArT+sDNCRUOYiAT91vPIL7cGla2HsPNMBoyfPY8g0IKkmboN+o9V5YZiPVhgknQ202Umq/vD/wzgoR5lKBJaIDsxAZnLNPClgHLsUk6AIYEgHkAKJzUOUQWkqSS3bI5EAHhw28GwwksG4bIaFk5/ZGMWeb27yivbRqrOuDH1qU2LjCBYCluiU2cYixwj8fbolj9vZ/Gw0BOm7ffgqH+1Jyuzgc=
  - secure: BYq6m40k83lM8z4ze/zzqcN+4hc3amYNxt5ceKf03dEHqd2/xLVG4mffxnbca0m7+2TTqKGYr2i6eP3Lr71WWakWYBBO0yi/exIxhwyIb2TIKmapqqZv5r5CrANvrRmdUyhYLBhJsxTn0FMuXcekoXLUiasY09KCsD6OnAMhCVh3MxwmjPXRpPTsqOKA6C3dCLw+Af83BbO+B6kXoX2YyGe2f73UQ+/nrjr/lMgFtm73m2dIdGuexihGaTWVdlrTQPWuDqFSqbX/FZ4MSeDCO+ax46WQpAFvK2RBOzxEPLZ4PKW2+Uxt5aVL2bAadyn1A5k2C8AI3K+1SGUl3xbhWLEU7N0kNcP0gF7d5fcK1HtKCN/+3z/Fyv5TeC5Fx/e5gP7QU7/AloDDsbbE3HPkp0NF2TWsFJmOZrW5mi3YkJzO622uFdJvxaSQmeuGX7cdoe9DMJ+TeTAk5W70WBd3XyOcx5cNt/qhmQ6c4fftaf/pI1LQdUUta7T0ObWVKlkKTtu8F8Oseb/bocWrXXWg5AYwjPUbDk36Jus2QYu17OAJQ9CS4W9M9aG7nqJVwwLW0Lj6XL81wZDHOeqzt2qAibIuI7n9Wa3j+5qrO9b5o3yXrkPD4Xii/RM3cu0qmCEi9xq74hoY38DxjGe4KqwIywyonr5NJMDJ0vFB+q2DrZU=
