#!/usr/bin/bash

WORKING=`pwd`

wget ${2:-http://archive.apache.org/dist/qpid/proton/0.13.1/qpid-proton-0.13.1.tar.gz} -O qpid-proton.tar.gz

mkdir qpid-proton-src build staging proton_build proton_install
tar -zxf qpid-proton.tar.gz -C qpid-proton-src --strip-components 1
cd proton_build
cmake -DBUILD_CPP=OFF -DBUILD_PERL=OFF -DBUILD_RUBY=OFF -DBUILD_JAVA=OFF -DBUILD_GO=ON -DBUILD_JAVASCRIPT=OFF -DBUILD_PHP=OFF $WORKING/qpid-proton-src/ && make && sudo make install
