package addresses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/EnMasseProject/enmasse-rest/models"
)

// CreateAddressReader is a Reader for the CreateAddress structure.
type CreateAddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateAddressCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateAddressDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewCreateAddressCreated creates a CreateAddressCreated with default headers values
func NewCreateAddressCreated() *CreateAddressCreated {
	return &CreateAddressCreated{}
}

/*CreateAddressCreated handles this case with default header values.

Address config response
*/
type CreateAddressCreated struct {
	/*The address config that was deployed
	 */
	Location string

	Payload models.AddressConfigMap
}

func (o *CreateAddressCreated) Error() string {
	return fmt.Sprintf("[POST /v1/enmasse/addresses][%d] createAddressCreated  %+v", 201, o.Payload)
}

func (o *CreateAddressCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Location
	o.Location = response.GetHeader("Location")

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAddressDefault creates a CreateAddressDefault with default headers values
func NewCreateAddressDefault(code int) *CreateAddressDefault {
	return &CreateAddressDefault{
		_statusCode: code,
	}
}

/*CreateAddressDefault handles this case with default header values.

Unexpected error
*/
type CreateAddressDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the create address default response
func (o *CreateAddressDefault) Code() int {
	return o._statusCode
}

func (o *CreateAddressDefault) Error() string {
	return fmt.Sprintf("[POST /v1/enmasse/addresses][%d] createAddress default  %+v", o._statusCode, o.Payload)
}

func (o *CreateAddressDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
