package addresses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/EnMasseProject/enmasse-rest/models"
)

// NewCreateAddressParams creates a new CreateAddressParams object
// with the default values initialized.
func NewCreateAddressParams() *CreateAddressParams {
	var ()
	return &CreateAddressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAddressParamsWithTimeout creates a new CreateAddressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateAddressParamsWithTimeout(timeout time.Duration) *CreateAddressParams {
	var ()
	return &CreateAddressParams{

		timeout: timeout,
	}
}

// NewCreateAddressParamsWithContext creates a new CreateAddressParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateAddressParamsWithContext(ctx context.Context) *CreateAddressParams {
	var ()
	return &CreateAddressParams{

		Context: ctx,
	}
}

/*CreateAddressParams contains all the parameters to send to the API endpoint
for the create address operation typically these are written to a http.Request
*/
type CreateAddressParams struct {

	/*AddressConfigMap
	  AddressConfig to create

	*/
	AddressConfigMap models.AddressConfigMap

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the create address params
func (o *CreateAddressParams) WithTimeout(timeout time.Duration) *CreateAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create address params
func (o *CreateAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create address params
func (o *CreateAddressParams) WithContext(ctx context.Context) *CreateAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create address params
func (o *CreateAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAddressConfigMap adds the addressConfigMap to the create address params
func (o *CreateAddressParams) WithAddressConfigMap(addressConfigMap models.AddressConfigMap) *CreateAddressParams {
	o.SetAddressConfigMap(addressConfigMap)
	return o
}

// SetAddressConfigMap adds the addressConfigMap to the create address params
func (o *CreateAddressParams) SetAddressConfigMap(addressConfigMap models.AddressConfigMap) {
	o.AddressConfigMap = addressConfigMap
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.AddressConfigMap); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
