package addresses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/EnMasseProject/enmasse-rest/models"
)

// NewDeleteAddressesParams creates a new DeleteAddressesParams object
// with the default values initialized.
func NewDeleteAddressesParams() *DeleteAddressesParams {
	var ()
	return &DeleteAddressesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAddressesParamsWithTimeout creates a new DeleteAddressesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAddressesParamsWithTimeout(timeout time.Duration) *DeleteAddressesParams {
	var ()
	return &DeleteAddressesParams{

		timeout: timeout,
	}
}

// NewDeleteAddressesParamsWithContext creates a new DeleteAddressesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAddressesParamsWithContext(ctx context.Context) *DeleteAddressesParams {
	var ()
	return &DeleteAddressesParams{

		Context: ctx,
	}
}

/*DeleteAddressesParams contains all the parameters to send to the API endpoint
for the delete addresses operation typically these are written to a http.Request
*/
type DeleteAddressesParams struct {

	/*AddressList
	  List of addresses

	*/
	AddressList models.AddressList

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the delete addresses params
func (o *DeleteAddressesParams) WithTimeout(timeout time.Duration) *DeleteAddressesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete addresses params
func (o *DeleteAddressesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete addresses params
func (o *DeleteAddressesParams) WithContext(ctx context.Context) *DeleteAddressesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete addresses params
func (o *DeleteAddressesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAddressList adds the addressList to the delete addresses params
func (o *DeleteAddressesParams) WithAddressList(addressList models.AddressList) *DeleteAddressesParams {
	o.SetAddressList(addressList)
	return o
}

// SetAddressList adds the addressList to the delete addresses params
func (o *DeleteAddressesParams) SetAddressList(addressList models.AddressList) {
	o.AddressList = addressList
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAddressesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.AddressList); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
