package addresses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/EnMasseProject/enmasse-rest/models"
)

// DeleteAddressesReader is a Reader for the DeleteAddresses structure.
type DeleteAddressesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAddressesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteAddressesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteAddressesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteAddressesOK creates a DeleteAddressesOK with default headers values
func NewDeleteAddressesOK() *DeleteAddressesOK {
	return &DeleteAddressesOK{}
}

/*DeleteAddressesOK handles this case with default header values.

Address config response
*/
type DeleteAddressesOK struct {
	Payload models.AddressConfigMap
}

func (o *DeleteAddressesOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/enmasse/addresses][%d] deleteAddressesOK  %+v", 200, o.Payload)
}

func (o *DeleteAddressesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAddressesDefault creates a DeleteAddressesDefault with default headers values
func NewDeleteAddressesDefault(code int) *DeleteAddressesDefault {
	return &DeleteAddressesDefault{
		_statusCode: code,
	}
}

/*DeleteAddressesDefault handles this case with default header values.

Unexpected error
*/
type DeleteAddressesDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the delete addresses default response
func (o *DeleteAddressesDefault) Code() int {
	return o._statusCode
}

func (o *DeleteAddressesDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/enmasse/addresses][%d] deleteAddresses default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteAddressesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
