package addresses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListAddressesParams creates a new ListAddressesParams object
// with the default values initialized.
func NewListAddressesParams() *ListAddressesParams {

	return &ListAddressesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAddressesParamsWithTimeout creates a new ListAddressesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAddressesParamsWithTimeout(timeout time.Duration) *ListAddressesParams {

	return &ListAddressesParams{

		timeout: timeout,
	}
}

// NewListAddressesParamsWithContext creates a new ListAddressesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAddressesParamsWithContext(ctx context.Context) *ListAddressesParams {

	return &ListAddressesParams{

		Context: ctx,
	}
}

/*ListAddressesParams contains all the parameters to send to the API endpoint
for the list addresses operation typically these are written to a http.Request
*/
type ListAddressesParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the list addresses params
func (o *ListAddressesParams) WithTimeout(timeout time.Duration) *ListAddressesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list addresses params
func (o *ListAddressesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list addresses params
func (o *ListAddressesParams) WithContext(ctx context.Context) *ListAddressesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list addresses params
func (o *ListAddressesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *ListAddressesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
