package addresses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/EnMasseProject/enmasse-rest/models"
)

// PutAddressesReader is a Reader for the PutAddresses structure.
type PutAddressesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAddressesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPutAddressesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPutAddressesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPutAddressesCreated creates a PutAddressesCreated with default headers values
func NewPutAddressesCreated() *PutAddressesCreated {
	return &PutAddressesCreated{}
}

/*PutAddressesCreated handles this case with default header values.

Address config response
*/
type PutAddressesCreated struct {
	/*The address config that was deployed
	 */
	Location string

	Payload models.AddressConfigMap
}

func (o *PutAddressesCreated) Error() string {
	return fmt.Sprintf("[PUT /v1/enmasse/addresses][%d] putAddressesCreated  %+v", 201, o.Payload)
}

func (o *PutAddressesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Location
	o.Location = response.GetHeader("Location")

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAddressesDefault creates a PutAddressesDefault with default headers values
func NewPutAddressesDefault(code int) *PutAddressesDefault {
	return &PutAddressesDefault{
		_statusCode: code,
	}
}

/*PutAddressesDefault handles this case with default header values.

Unexpected error
*/
type PutAddressesDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the put addresses default response
func (o *PutAddressesDefault) Code() int {
	return o._statusCode
}

func (o *PutAddressesDefault) Error() string {
	return fmt.Sprintf("[PUT /v1/enmasse/addresses][%d] putAddresses default  %+v", o._statusCode, o.Payload)
}

func (o *PutAddressesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
