package addresses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/EnMasseProject/enmasse-rest/models"
)

// NewDeleteAddressesParams creates a new DeleteAddressesParams object
// with the default values initialized.
func NewDeleteAddressesParams() DeleteAddressesParams {
	var ()
	return DeleteAddressesParams{}
}

// DeleteAddressesParams contains all the bound params for the delete addresses operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteAddresses
type DeleteAddressesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*List of addresses
	  Required: true
	  In: body
	*/
	AddressList models.AddressList
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *DeleteAddressesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.AddressList
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("addressList", "body"))
			} else {
				res = append(res, errors.NewParseError("addressList", "body", "", err))
			}

		} else {

			if len(res) == 0 {
				o.AddressList = body
			}
		}

	} else {
		res = append(res, errors.Required("addressList", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
