package addresses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAddressesHandlerFunc turns a function with the right signature into a get addresses handler
type GetAddressesHandlerFunc func(GetAddressesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAddressesHandlerFunc) Handle(params GetAddressesParams) middleware.Responder {
	return fn(params)
}

// GetAddressesHandler interface for that can handle valid get addresses params
type GetAddressesHandler interface {
	Handle(GetAddressesParams) middleware.Responder
}

// NewGetAddresses creates a new http.Handler for the get addresses operation
func NewGetAddresses(ctx *middleware.Context, handler GetAddressesHandler) *GetAddresses {
	return &GetAddresses{Context: ctx, Handler: handler}
}

/*GetAddresses swagger:route GET /addressconfig addresses getAddresses

Returns the addressing configuration for the cluster

*/
type GetAddresses struct {
	Context *middleware.Context
	Handler GetAddressesHandler
}

func (o *GetAddresses) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetAddressesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
