---
swagger: "2.0"
info:
  title: Enmasse Rest
  description: |-
    The REST API server for the EnMasse messaging service
  version: "0.0.0"
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
definitions:
  ErrorModel:
    properties:
      status:
        description: |-
          HTTP status code
        type: integer
        format: int32
      title:
        description: |-
          A brief summary of the error, this should remain consistent
          between errors of the same class
        type: string
      details:
        description: |-
          An explanation of the specific error that has occurred
        type: string
    required:
      - status
      - title
      - details
  ErrorResponse:
    properties:
      errors:
        description: |-
          List of errors returned
        type: array
        minItems: 1
        items:
          $ref: "#/definitions/ErrorModel"
    required:
      - errors
  AddressConfig:
    required:
      - store_and_forward
      - multicast
    properties:
      store_and_forward:
        type: boolean
      multicast:
        type: boolean
      flavor:
        type: string
        
  AddressConfigMap:
    type: object
    additionalProperties:
      $ref: '#/definitions/AddressConfig'
paths:
  /v1/enmasse/addresses:
    get:
      description: |-
        Returns the addressing configuration for the cluster
      operationId: listAddresses
      tags:
        - addresses
      responses:
        "200":
          description: |-
            Address config response
          schema:
            $ref: "#/definitions/AddressConfigMap"
        default:
          description: |-
            Unexpected error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: |-
        Create address config
      operationId: createAddress
      tags:
        - addresses
      parameters:
        - name: addressConfigMap
          in: body
          description: AddressConfig to create
          required: true
          schema:
            $ref: "#/definitions/AddressConfigMap"
      responses:
        "201":
          description: |-
            Address config response
          headers:
            Location:
              description: |-
                The address config that was deployed
              type: string
          schema:
            $ref: "#/definitions/AddressConfigMap"
        default:
          description: |-
            Unexpected error
          schema:
            $ref: "#/definitions/ErrorResponse"
