package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// AddressConfig address config
// swagger:model AddressConfig
type AddressConfig map[string]AddressSpec

// Validate validates this address config
func (m AddressConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", AddressConfig(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
